app:
  encoding: @project.build.sourceEncoding@
  java:
    version: @java.version@
server:
  port: 8081
  servlet:
    contextPath: /admin
  undertow:
    io-threads: 1
    worker-threads: 2
    buffer-size: 1024
    direct-buffers: true
spring:
  mvc:
    static-path-pattern: /**
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.176.40:3306/smart_net
    username: root
    password: Stream1234
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: blah
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
  messages:
    basename: i18n/message
  data:
    web:
      pageable:
        one-indexed-parameters: true
        page-parameter: page
        size-parameter: limit
  thymeleaf:
    cache: false